%% QUESTION INFO

% An infinite uniform linear charge p_L= 2.0 nC/m lies along the x axis in free space, 
% while point charges  of  8.0  nC  each  are  located  at  (0,  0,  1)  and  (0,  0,  -1).    
% Find  E  at  (2,  3,  4).    
% Write  a  MATLAB program to verify your answer.



%% SOLUTION

clc; %clear the command line 
clear; %remove all previous variables 
Q1=8e-9; %charges on Q1 
Q2=8e-9; %charges on Q2 
pL=2e-9; %charge density of the line  
Epsilono=8.8419e-12; %Permitivity of free space 

P=[2 3 4]; %coordinates of observation point 
A=[0 0 1]; %coordinates of Q1 
B=[0 0 -1]; %coordinates of Q2 
C=[2 0 0]; %coordinates of the center of the line charge 
Number_of_L_Steps=100000; %the steps of L

%% the following routine calculates the electric fields at the observation point generated by the point charges 
R1=P-A; %the vector pointing from Q1 to the observation point 
R2=P-B; %the vector pointing from Q2 to the observation point 
R1Mag=norm(R1); %the magnitude of R1
R2Mag=norm(R2); %the magnitude of R1 
E1=Q1/(4*pi*Epsilono*R1Mag^3)*R1; %the electric field generated by Q1 
E2=Q2/(4*pi*Epsilono*R2Mag^3)*R2; %the electric field generated by Q2 

%% the following routine calculates the electric field at the observation point generated by the line charge  
d=norm(P-C); %the distance from the observation point to the center of the line 
length=100*d; %the length of the line 
dL_V=length/Number_of_L_Steps*[1 0 0]; %vector of a segment 
dL=norm(dL_V); %length of a segment 
EL=[0 0 0]; %initialize the electric field generated by EL 
C_segment=C-( Number_of_L_Steps/2*dL_V-dL_V/2); %the center of the first segment 

for i=1: Number_of_L_Steps
    R=P-C_segment; %the vector seen from the center of the first segment to the observation point     
    RMag=norm(R); %the magnitude of the vector R     
    EL=EL+dL*pL/(4*pi*Epsilono*RMag^3)*R; %get contibution from each segment      
    C_segment=C_segment+dL_V; %the center of the i-th segment 
end 

E=E1+E2+EL; %the electric field at P
